services:
  clever-crm_be:
    container_name: clever-crm_be
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - '4000:4000'
    depends_on:
      db:
        condition: service_healthy
    # healthcheck:
    #   test: ["CMD-SHELL", "curl -f http://localhost:4000/health"] //TODO: add endpoint
    #   interval: 30s
    #   timeout: 10s
    #   retries: 5
    # restart: unless-stopped
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 60s
    volumes:
      - ./src:/app/src
    networks:
      - cleverNetwork

  db:
    container_name: clever-crm_db
    image: postgres:17.1
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U tarasPG']
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    networks:
      - cleverNetwork

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: pgadmin
    env_file:
      - .env
    ports:
      - '5050:80'
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ['CMD-SHELL', 'curl -f http://localhost/pgadmin4']
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    networks:
      - cleverNetwork

volumes:
  db-data:
  pgadmin-data:

networks:
  cleverNetwork:
    name: cleverNetwork
    driver: bridge
